### ISSUE TITLE
Clarify stance on platform-specific/"native" UI API usage

### ISSUE THREAD

**Issue by mitchmindtree** [ruiwg/about-us#3]
To clarify, I mean whether or not the framework is willing to try and abstract the native UI "widgets" behind some kind of generic API, or whether the project aims to provide custom "widgets" built from the ground up. E.g. if a "Slider" widget/element was provided, would it be an attempt at abstracting around the native slider on each of those platforms (e.g. some cocoa thing on macOS, etc), or would its behaviour/style/rendering be implemented from the ground up  in a custom solution?

I am personally uninterested in attempting to call into platform-specific UI APIs for each platform and would prefer widgets/elements were implemented from the ground-up where possible, even if we were to aim for "native-looking" styling on each platform. By having the implementation in Rust from the ground up we gain a lot more control, remove the need for a lot of unsafe FFI work, and remove the need to try and adapt to the extensive differences in platform-specific APIs.

That said, there are of course cases where interacting with the platform is unavoidable or desired. I think this kind of code is best encapsulated in dedicated cross-platform libraries - [winit](https://github.com/rust-windowing/winit) (windowing and input events), [cpal](https://github.com/rustaudio/cpal) (audio I/O) and [copypasta](https://github.com/jwilm/alacritty/tree/master/copypasta) (clipboard) come to mind as good examples.

> While we welcome non-Rust language interfaces, we will never compromise the usability and quality of the Rust API to meet their needs.

This implies to me that we have similar goals in mind, but I just wanted to hear your thoughts

**Comment by Xaeroxe** [comment]
I would phrase my stance on this as "custom widgets first, native widgets maybe."

To clarify that further, in my world view, the data model will provide a specification for how each element should look when rendered. If you can meet that specification with a native framework, I see no reason to stop you. However, the working group is unlikely to ever support these native widget renderers directly. They would be started and maintained by external community members. Additionally, decision making about the UI memory model will not be restrained by constraints imposed by native widget frameworks.
